apiVersion: v1
kind: Service
metadata:
  name: lb-nginx
  labels:
    app: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 192.168.99.101
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 80
    - port: 443
      name: https
      protocol: TCP
      targetPort: 443
    - port: 22
      name: ssh
      protocol: TCP
      targetPort: 22
  selector:
    app: my-nginx