
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
        - image: nginx:latest
          imagePullPolicy: Never
          name: nginx
          ports:
            - containerPort: 80
            - containerPort: 22
            - containerPort: 443