apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    app: php
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 192.168.99.101
  ports:
    - port: 5000
      name: http
      protocol: TCP
      targetPort: 5000
  selector:
    app: php